version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    

  postgres:
    image: postgres:latest

    environment:
      - POSTGRES_DB =localdb
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:


      