[tool.poetry]
name = "rbac project"
version = "0.1.0"
description = ""
authors = ["Ojo Peter <ojopeter36@gmail.com>"]
license = "MIT"


[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
pydantic = {extras = ["email"], version = "^2.4.1"}

uvicorn = "^0.23.2"
httptools = "^0.6.0"
uuid = "^1.30"
alembic = "^1.12.0"
asyncpg = "^0.28.0"
SQLAlchemy-Utils = "^0.41.1"
python-jose = "^3.3.0"
passlib = "^1.7.4"
SQLAlchemy = "^2.0.21"
pytest = "^7.4.2"
python-multipart = "^0.0.6"
greenlet = "^2.0.2"
httpx = "^0.25.0"
pydantic-settings = "^2.0.3"
redis = "^5.0.1"
arq = "0.25.0"
gunicorn = "^21.2.0"
fastapi-mail = "^1.4.1"
psycopg2-binary = "^2.9.9"
aiosmtplib = "2.0.2"
annotated-types = "0.6.0"
async-timeout = "4.0.3"
blinker = "1.7.0"
certifi = "2023.11.17"
click = "8.1.7"
colorama = "0.4.6"
dnspython = "2.5.0"
fastapi = "^0.109.0"
anyio = "^4.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
